# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Calc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Calc.proto',
  package='calc',
  syntax='proto3',
  serialized_pb=_b('\n\nCalc.proto\x12\x04\x63\x61lc\",\n\x0ctitleRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"(\n\tStringInt\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\",\n\tOnetReply\x12\x1f\n\x06result\x18\x01 \x03(\x0b\x32\x0f.calc.StringInt2>\n\nCalculator\x12\x30\n\x07GetOnet\x12\x12.calc.titleRequest\x1a\x0f.calc.OnetReply\"\x00\x62\x06proto3')
)




_TITLEREQUEST = _descriptor.Descriptor(
  name='titleRequest',
  full_name='calc.titleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='calc.titleRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='calc.titleRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)


_STRINGINT = _descriptor.Descriptor(
  name='StringInt',
  full_name='calc.StringInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='calc.StringInt.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='calc.StringInt.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=106,
)


_ONETREPLY = _descriptor.Descriptor(
  name='OnetReply',
  full_name='calc.OnetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calc.OnetReply.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=152,
)

_ONETREPLY.fields_by_name['result'].message_type = _STRINGINT
DESCRIPTOR.message_types_by_name['titleRequest'] = _TITLEREQUEST
DESCRIPTOR.message_types_by_name['StringInt'] = _STRINGINT
DESCRIPTOR.message_types_by_name['OnetReply'] = _ONETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

titleRequest = _reflection.GeneratedProtocolMessageType('titleRequest', (_message.Message,), dict(
  DESCRIPTOR = _TITLEREQUEST,
  __module__ = 'Calc_pb2'
  # @@protoc_insertion_point(class_scope:calc.titleRequest)
  ))
_sym_db.RegisterMessage(titleRequest)

StringInt = _reflection.GeneratedProtocolMessageType('StringInt', (_message.Message,), dict(
  DESCRIPTOR = _STRINGINT,
  __module__ = 'Calc_pb2'
  # @@protoc_insertion_point(class_scope:calc.StringInt)
  ))
_sym_db.RegisterMessage(StringInt)

OnetReply = _reflection.GeneratedProtocolMessageType('OnetReply', (_message.Message,), dict(
  DESCRIPTOR = _ONETREPLY,
  __module__ = 'Calc_pb2'
  # @@protoc_insertion_point(class_scope:calc.OnetReply)
  ))
_sym_db.RegisterMessage(OnetReply)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calc.Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=154,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOnet',
    full_name='calc.Calculator.GetOnet',
    index=0,
    containing_service=None,
    input_type=_TITLEREQUEST,
    output_type=_ONETREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
